---
name: iRODS
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge:python=3.8.5
  - conda-forge:pytest=6.0.1
  - conda-forge:datrie=0.8.2
  - conda-forge:git=2.28.0
  - conda-forge:jinja2=2.11.2
  - conda-forge:pygraphviz=1.5
  - conda-forge:flask=1.1.2
  - conda-forge:pandas=1.1.0
  - conda-forge:zlib=1.2.11
  - conda-forge:openssl=1.1.1g
  - conda-forge:networkx=2.4
  - bioconda:snakemake=5.20.1
  - conda-forge:black=19.10b0
  - conda-forge:ipython=7.17.0
  - conda-forge:bashlex=0.15
